content:
  - name: users
    label: Employees
    path: _posts
    type: collection
    view:
      fields: [name, id, active, date, training, feats, stacks]
      default:
        sort: date
        order: desc
    fields:
      - name: id
        label: "ID"
        type: number
        required: true
        description: "Employee #."
      - name: name
        label: "Name"
        type: string
        required: true
        description: "Employee Name: First Name + Last Name."
      - name: date
        label: "Hire Date"
        type: date
        default: ""
        options:
          format: yyyy-MM-dd
        required: true
        description: "Date this employee has hired on."
      - name: active
        label: "Active?"
        type: boolean
        default: true
        required: true
      - name: achievements
        label: "Achievements"
        list: true
        type: block
        blocks:
        - name: runner_i
          label: "Runner I" 
          type: boolean
          default: false
        - name: runner_ii
          label: "Runner II" 
          type: boolean
          default: false