content:
  - name: users
    label: Employees
    path: _posts
    type: collection
    view:
      fields: [id, name, active, date, training, feats, stacks]
      default:
        sort: date
        order: desc
    fields:
      - name: id
        label: "ID"
        type: number
        required: true
        description: "Employee #."
      - name: name
        label: "Name"
        type: string
        required: true
        description: "Employee Name: First Name + Last Name."
      - name: date
        label: "Hire Date"
        type: date
        default: ""
        options:
          format: yyyy-MM-dd
        required: true
        description: "Date this employee has hired on."
      - name: active
        label: "Active?"
        type: boolean
        default: true
        required: true
      - name: training
        label: "Training Achievements"
        list: true
        type: object
        list: true
        fields:
        - name: training_select
          label: "Achivement Selection" 
          type: reference
          options:
            collection: training
            value: "{namespace}"
            label: "{fields.name} ({fields.description})"
        - name: completed
          label: "Is it completed?"
          type: boolean
          required: true
      - name: feats
        label: "One-Time Achievements"
        list: true
        type: object
        list: true
        fields:
        - name: feats_select
          label: "Achivement Selection" 
          type: reference
          options:
            collection: feat
            value: "{namespace}"
            label: "{fields.name} ({fields.description})"
        - name: completed
          label: "Is it completed?"
          type: boolean
          required: true
      - name: stacks
        label: "Stackable Achievements"
        list: true
        type: object
        list: true
        fields:
        - name: stacks_select
          label: "Achivement Selection" 
          type: reference
          options:
            collection: stackable
            value: "{namespace}"
            label: "{fields.name} ({fields.description})"
        - name: times
          label: "Times Awarded"
          type: number
          required: true
          options:
            min: 0
  - name: training
    label: "Training Achievements"
    path: _training
    type: collection
    fields:
    - name: name
      label: "Name"
      type: string
      required: true
    - name: description
      label: "Description"
      type: string
      required: true
    - name: reward_title
      label: "Title"
      type: string
      required: true
    - name: reward_item
      label: "Reward"
      type: string
    - name: points
      label: "Points"
      type: number
      required: true
      options:
        min: 0
    - name: namespace
      label: "ID"
      type: string
      required: true
  - name: feat
    label: "One Time Achievements"
    path: _feat
    type: collection
    fields:
    - name: name
      label: "Name"
      type: string
      required: true
    - name: description
      label: "Description"
      type: string
      required: true
    - name: reward_title
      label: "Title"
      type: string
      required: true
    - name: reward_item
      label: "Reward"
      type: string
    - name: points
      label: "Points"
      type: number
      required: true
      options:
        min: 0
    - name: namespace
      label: "ID"
      type: string
      required: true
  - name: stackable
    label: "Stackable Achievements"
    path: _stackable
    type: collection
    fields:
    - name: name
      label: "Name"
      type: string
      required: true
    - name: description
      label: "Description"
      type: string
      required: true
    - name: reward_title
      label: "Title"
      type: string
      required: true
    - name: reward_item
      label: "Reward"
      type: string
    - name: points
      label: "Points"
      type: number
      required: true
      options:
        min: 0
    - name: namespace
      label: "ID"
      type: string
      required: true