content:
  - name: users
    label: Employees
    path: _posts
    type: collection
    fields:
      - name: id
        label: "ID"
        type: number
        required: true
        description: "Employee #."
      - name: name
        label: "Name"
        type: string
        required: true
        description: "Employee Name: First Name + Last Name."
      - name: date
        label: "Hire Date"
        type: date
        default: ""
        options:
          format: yyyy-MM-dd
        required: true
        description: "Date this employee has hired on."
      - name: training
        label: "Training Achievements"
        type: reference
        options:
          collection: training
          value: "{namespace}"
          label: "{fields.name} ({fields.description})"
  - name: training
    label: "Training"
    path: _training
    type: collection
    fields:
    - name: name
      label: "Name"
      type: string
      required: true
    - name: description
      label: "Description"
      type: string
      required: true
    - name: reward_title
      label: "Title"
      type: string
      required: true
    - name: reward_item
      label: "Reward"
      type: string
    - name: points
      label: "Points"
      type: number
      required: true
      options:
        min: 0
    - name: namespace
      label: "ID"
      type: string
      required: true
  - name: feat
    label: "Feats"
    path: _feat
    type: collection
    fields:
    - name: name
      label: "Name"
      type: string
      required: true
    - name: description
      label: "Description"
      type: string
      required: true
    - name: reward_title
      label: "Title"
      type: string
      required: true
    - name: reward_item
      label: "Reward"
      type: string
    - name: points
      label: "Points"
      type: number
      required: true
      options:
        min: 0
    - name: namespace
      label: "ID"
      type: string
      required: true
  - name: stackable
    label: "Stackable Achievements"
    path: _stackable
    type: collection
    fields:
    - name: name
      label: "Name"
      type: string
      required: true
    - name: description
      label: "Description"
      type: string
      required: true
    - name: reward_title
      label: "Title"
      type: string
      required: true
    - name: reward_item
      label: "Reward"
      type: string
    - name: points
      label: "Points"
      type: number
      required: true
      options:
        min: 0
    - name: times
      label: "Times Awarded"
      type: number
      required: true
      options:
        min: 0
    - name: namespace
      label: "ID"
      type: string
      required: true