name: Optimize Images

on:
  workflow_dispatch:
  push:
    paths:
      - 'assets/img/avatars/raw/*'

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get install imagemagick -y

      - name: Convert images to webp
        run: |
          mkdir -p assets/img/avatars
          for file in assets/img/avatars/raw/*; do
            filename=$(basename "$file")
            name="${filename%.*}"

            convert "$file" -quality 75 "assets/img/avatars/${name}.webp"
          done

      - name: Remove raw images
        run: rm -f assets/img/avatars/raw/*

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add assets/img/avatars
          git rm -f assets/img/avatars/raw/* || true
          git commit -m "Optimize and convert avatars to webp" || echo "No changes"
          git push
